name: macOS with TSan

on:
  workflow_dispatch:
  push:

jobs:
  build-macos:
    runs-on: macos-26
    env:
      # -fsanitize=memtag-stack -march=armv8a+memtag only with M5 CPU
      # CFLAGS: '-fsanitize-address-use-after-scope -fsanitize-coverage=trace-cmp -fstack-clash-protection'
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      PYTHONSTRICTEXTENSIONBUILD: 1
      MACOSX_DEPLOYMENT_TARGET: 10.15
      LDFLAGS: "-L/opt/homebrew/opt/llvm/lib"
      CPPFLAGS: "-I/opt/homebrew/opt/llvm/include"
      CC: 'clang-22'

    steps:
    - uses: actions/checkout@v6
      with:
        repository: "python/cpython"

#    - name: Change recursion
#      run: sed -i '' 's/150_000/300_000/g' Lib/test/support/__init__.py

    - name: Install Homebrew dependencies
      run: |
        brew bundle --file=Misc/Brewfile
        brew install make llvm
        echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> "$GITHUB_ENV"
#        export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
#        ls /opt/homebrew/opt/llvm/bin
#        env

#    - name: System info
#      run: |
#        $CC --version
#        system_profiler SPHardwareDataType

    - name: Configure no-GIL with TSan
      run: |
        GDBM_CFLAGS="-I$(brew --prefix gdbm)/include" \
        GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm" \
          ./configure \
            --with-thread-sanitizer \
            --disable-gil \
            --prefix=/opt/python-dev \

    - name: Upload config.log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: config-log
        path: 'config.log'
  
    - name: Make
      run: gmake -j

#    - name: Display build info
#      run: gmake pythoninfo

    - name: Tests
      run: gmake ci
          
