name: Makefile CI

on:
  schedule:
    - cron: "0 2 */2 * *"
  workflow_dispatch:
  push:

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      CC: 'clang'
      CFLAGS: |
        -fsanitize=memtag-stack -fsanitize=undefined
        -fsanitize-address-use-after-scope -fsanitize-coverage=trace-cmp
        -fstack-clash-protection
        -march=armv8a+memtag

    steps:
    - uses: actions/checkout@v6
      with:
        repository: "python/cpython"

    - name: Configure no-GIL with HWAddress, memtag-stack, LSan, UBSan, Type Sanitizer, MSan
      run: |
          ./configure \
            --with-undefined-behavior-sanitizer
            --disable-gil
            --enable-safety
            --config-cache
            --with-lto=yes

    - name: Upload config.log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: config-log
        path: 'config.log'
  
    - name: Make
      run: make -j8 --output-sync

    - name: Display build info
      run: make pythoninfo

    - name: Tests
      run: make ci
          
