name: Makefile CI

on:
  schedule:
    - cron: "0 2 */2 * *"
  workflow_dispatch:
  push:

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      CFLAGS: |
        "-fsanitize=hwaddress -fsanitize=memtag-stack -fsanitized=undefined \
        -fsanitize-address-use-after-scope -fsanitize-coverage=trace-cmp \
        -fharden-compares -fharden-conditional-branches -fharden-control-flow-redundancy \
        -fhardcfr-check-returning-calls -fstack-check -fstack-clash-protection \
        -fsanitize=leak"

    steps:
    - uses: actions/checkout@v6
      with:
        repository: "python/cpython"

    - name: Configure no-GIL with HWAddress, memtag-stack, LSan, UBSan, Type Sanitizer, MSan
      run: |
          ./configure --with-undefined-behavior-sanitizer --disable-gil --enable-safety --config-cache
          if [[$? -ne 0]]; then
            cat config.log
          fi
  
    - name: Make
      run: make -j8 --output-sync

    - name: Display build info
      run: make pythoninfo

    - name: Tests
      run: make ci
          
