name: Makefile CI

on:
  schedule:
    - cron: "0 2 */2 * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        repository: "python/cpython"

    - name: Configure no-GIL with HWAddress, memtag-stack, LSan, UBSan, Type Sanitizer, MSan
      run: |
        
        CFLAGS="-fsanitize=hwaddress -fanitize=memtag-stack \
          -fsanitize=leak  \
          -fsanitize=type -fsanitize=memory" \
          ./configure --with-undefined-behavior-sanitizer --disable-gil --enable-safety

    - name: Install dependencies
      run: make -j4

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
          
